# Generated by Django 4.2.6 on 2023-11-17 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='patient_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
