# Generated by Django 4.2.6 on 2023-10-23 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='insurance',
            name='id',
        ),
        migrations.AlterField(
            model_name='insurance',
            name='insurancename',
            field=models.CharField(max_length=300, primary_key=True, serialize=False, unique=True),
        ),
    ]
