# Generated by Django 4.2.6 on 2023-10-25 12:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('treatment', '0002_remove_intervention_id_alter_intervention_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('treatmentamount', models.IntegerField(blank=True, null=True)),
                ('partinsurance', models.IntegerField()),
                ('partpatient', models.IntegerField()),
                ('amountpaid', models.IntegerField()),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('registered_on', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='patient.patient')),
                ('treatment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='treatment.treatment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-registered_on'],
            },
        ),
    ]
