# Generated by Django 4.2.6 on 2023-10-24 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='rendezvoustime',
            field=models.TimeField(),
        ),
    ]
