# Generated by Django 4.2.6 on 2023-10-24 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treatment', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='intervention',
            name='id',
        ),
        migrations.AlterField(
            model_name='intervention',
            name='name',
            field=models.CharField(max_length=300, primary_key=True, serialize=False, unique=True),
        ),
    ]
