# Generated by Django 4.2.6 on 2023-11-01 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinicinfo',
            name='telephonemobile',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='clinicinfo',
            name='telephonemobile2',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
