# Generated by Django 4.2.6 on 2023-11-08 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0002_clinicinfo_telephonemobile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinicinfo',
            name='telephone',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='clinicinfo',
            name='telephonemobile',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='clinicinfo',
            name='telephonemobile2',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
