# Generated by Django 4.2.6 on 2023-10-23 10:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('insurance', '0002_remove_insurance_id_alter_insurance_insurancename'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('MALE', 'Male'), ('FEMELE', 'Femele'), ('OTHER', 'Autre')], max_length=15)),
                ('firstname', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=100)),
                ('dob', models.DateField()),
                ('profession', models.CharField(max_length=200)),
                ('telephone', models.CharField(blank=True, max_length=20, null=True)),
                ('insurance_matricule', models.CharField(max_length=200)),
                ('insurance_pourcentage', models.IntegerField()),
                ('email', models.EmailField(max_length=150, verbose_name='email address')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('insurance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='insurance.insurance')),
            ],
            options={
                'ordering': ['-created_date'],
            },
        ),
    ]
