# Generated by Django 4.2.6 on 2023-12-07 09:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0002_remove_insurance_id_alter_insurance_insurancename'),
        ('patient', '0004_patientmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='insurance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='insurance.insurance'),
        ),
    ]
